name: Actions test

on:
  push:
    branches:
      - main

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: RSS Feed Fetch Action
      uses: Promptly-Technologies-LLC/rss-fetch-action@v2.1
      with:
        feed_url: 'https://defence-blog.com/feed/'
        file_path: './data/feed.json'
    
    - name: Commit and push changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update RSS feed'
        file_pattern: '*.json'
