name: "RSS Feed - defense-blog.com"

on:
  schedule:
    - cron: '0 * * * *'
  
  workflow_dispatch:
  
permissions:
   contents: write
  
jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:       
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch RSS Feed
      uses: Promptly-Technologies-LLC/rss-fetch-action@v2
      with:
        feed_url: https://defence-blog.com/feed/atom/
        file_path: './data/defence_blog.json'
        parser_options: "{\"useISODateFormat\": false, \"getExtraEntryFields\": \"(feedEntry) => { return { 'summary': feedEntry['summary'] || '', 'author': feedEntry['author'], 'category': feedEntry['category']['@_term'] }; }\"}"
        fetch_options: "{\"headers\": {\"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0\",\"Accept\": \"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\"}}"
    
    - name: Commit and push changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ github.event.repository.updated_at}}
        file_pattern: '*.json'
