name: Actions Test

on:
  push:
    branches:
      - main

jobs:
  update-log:
    name: Update with response
    runs-on: ubuntu-latest
    steps:
      - uses: i-valchev/rss-to-json@v1.0.0
        with: 
          source: feeds.yaml
