name: "Manual RSS Feed - Output to JSON"
on:
  workflow_dispatch:
    inputs:
      feed_url:
        description: "URL of RSS feed to be read"
        type: string
        required: true
        default: 'https://defence-blog.com/feed/'
      script_output:
        description: "Output of the script (e.g. issue, json, pull_request)"
        type: string
        required: true
        default: 'json'
permissions:
  read-all
  write-all
  
jobs:
  manual_rss_feed_execution:
    runs-on: ubuntu-latest
    steps: 
      - uses: chrisreddington/rss-parser-action@main
        with:
          feed_url: ${{ inputs.feed_url }}
          script_output: ${{ inputs.script_output }}
