name: Actions Test

on:
  push:
    branches:
      - main
permissions:
   id-token: write
   contents: read
   
jobs:
  update-log:
    name: Update with response
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/I-Valchev/rss-to-json@1.0.0
