name: Actions Test

on:
  push:
    branches:
      - main

jobs:
  update-log:
    name: Update with response
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: i-valchev/rss-to-json@1.0.0
