name: Merge Files
on:
  [push]

permissions:
   contents: write

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:       
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run Python
      run: |
        python python/main.py
        
    - name: Commit
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m 'Bot: Updated data.json'
        git push
