name: Merge Files
on:
  workflow_dispatch

permissions:
   contents: write

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:       
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run Python
      run: |
        python python/main.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "crongenerated"
        git push
