name: Merge Files
on:
  workflow_dispatch

permissions:
   contents: write

jobs:
  merge-files:
    runs-on: ubuntu-latest

    steps:       
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        run: |
          python python/main.py
