name: "RSS Feed - defense-blog.com 2"

on:
  schedule:
    - cron: '0 * * * *'
  
  workflow_dispatch:
  
permissions:
   contents: write
  
jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:       
    - name: Checkout code
      uses: actions/checkout@v4

    - name: RSS to JSON
      uses: I-Valchev/rss-to-json@1.0.0
    
    - name: Commit and push changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ github.event.repository.updated_at}}
        file_pattern: '*.json'
